/* Write your PL/SQL query statement below */
/* Write your PL/SQL query statement below */
--RANA
WITH HOST_POINTS AS(
    SELECT M.HOST_TEAM AS HH, SUM(
        CASE 
            WHEN M.HOST_GOALS > M.GUEST_GOALS THEN 3
            WHEN M.HOST_GOALS = M.GUEST_GOALS THEN 1
            WHEN M.HOST_GOALS < M.GUEST_GOALS THEN 0
        END
    )AS HPOINTS FROM MATCHES M
    GROUP BY M.HOST_TEAM
),GUEST_POINTS AS(
    SELECT M1.GUEST_TEAM AS GG, SUM(
        CASE 
            WHEN M1.HOST_GOALS < M1.GUEST_GOALS THEN 3
            WHEN M1.HOST_GOALS = M1.GUEST_GOALS THEN 1
            WHEN M1.HOST_GOALS > M1.GUEST_GOALS THEN 0
        END
    )AS GPOINTS FROM MATCHES M1
    GROUP BY M1.GUEST_TEAM 
),POINTS AS(
    SELECT H.HH AS TEAM_ID, (NVL(H.HPOINTS,0) + NVL(G.GPOINTS,0)) AS NUM_POINTS
    FROM HOST_POINTS H LEFT JOIN GUEST_POINTS G
    ON (H.HH = G.GG) UNION 
    SELECT G.GG AS TEAM_ID, (NVL(H.HPOINTS,0) + NVL(G.GPOINTS,0)) AS NUM_POINTS
    FROM HOST_POINTS H RIGHT JOIN GUEST_POINTS G
    ON (H.HH = G.GG)
) SELECT T.TEAM_ID , T.TEAM_NAME, NVL(P.NUM_POINTS,0) AS NUM_POINTS
  FROM TEAMS T LEFT JOIN POINTS P 
  ON(T.TEAM_ID = P.TEAM_ID)
  ORDER BY NUM_POINTS DESC, T.TEAM_ID ASC;
